source 'https://rubygems.org'

gem 'jekyll', '~> 3.1.6'
gem 'albino', '1.3.3'
gem 'bootstrap-sass'
gem 'foreman'
gem 'compass'
gem 'rake'
gem 'syck'
gem 'kramdown', '1.11.1'
gem 'safe_yaml', '~> 1.0.4'
gem 'redcarpet'
gem 'jekyll-paginate'
gem 'pygmentize'
